from typing import Protocol, Dict, Any

class Exchange(Protocol):
    async def get_price(self, symbol: str) -> float: ...
    async def get_exchange_info(self) -> Dict[str, Any]: ...
    async def place_order(self, symbol: str, side: str, type_: str, quantity: float, price: float | None = None, client_id: str | None = None) -> Dict[str, Any]: ...
    async def cancel(self, symbol: str, order_id: str | None = None, client_id: str | None = None) -> Dict[str, Any]: ...
    async def get_balance(self, asset: str) -> float: ...
